# Generated by Django 4.1.3 on 2022-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=15, verbose_name='nombre rol'),
        ),
    ]
