# Generated by Django 4.1.3 on 2022-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('id_card', models.CharField(max_length=20, unique=True, verbose_name='cedula')),
                ('type_card', models.CharField(max_length=20, verbose_name='Tipo de documento')),
                ('first_name_user', models.CharField(max_length=15, verbose_name='primer nombre')),
                ('sec_name_user', models.CharField(max_length=15, verbose_name='segundo nombre')),
                ('first_lastname_user', models.CharField(max_length=15, verbose_name='primer apellido')),
                ('sec_lastname_user', models.CharField(max_length=15, verbose_name='segundo apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('city', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
