# Generated by Django 4.1.3 on 2022-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sec_lastname_user',
            field=models.CharField(max_length=15, null=True, verbose_name='segundo apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sec_name_user',
            field=models.CharField(max_length=15, null=True, verbose_name='segundo nombre'),
        ),
    ]
