# Generated by Django 4.1.3 on 2022-12-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_sec_lastname_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_lastname_user'], 'verbose_name': 'User', 'verbose_name_plural': ' Users'},
        ),
    ]
