# Generated by Django 4.1.3 on 2023-01-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='.\\static\\media\\images_pdf\\logo.png', null=True, upload_to='app1/images/'),
        ),
    ]
