# Generated by Django 4.1.3 on 2023-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='number_measurer',
        ),
        migrations.AlterField(
            model_name='bill',
            name='concepts',
            field=models.TextField(max_length=200, unique=True, verbose_name='conceptos'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='other_charges',
            field=models.IntegerField(blank=True, null=True, verbose_name='Otros cargos '),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_consumption',
            field=models.IntegerField(verbose_name='Total a pagar por consumo'),
        ),
    ]
