# Generated by Django 4.1.3 on 2023-01-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_bill_number_measurer_alter_bill_concepts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='iva',
        ),
    ]
