# Generated by Django 4.1.3 on 2023-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_bill_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(max_length=30, null=True, verbose_name='Tipo de cliente'),
        ),
    ]
