# Generated by Django 4.1.3 on 2023-01-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_client_type_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
