# Generated by Django 4.1.3 on 2023-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_bill_basic_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='legal_entity',
            name='commercial_rate',
        ),
        migrations.RemoveField(
            model_name='natural_person',
            name='residential_rate',
        ),
        migrations.AddField(
            model_name='legal_entity',
            name='Phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono del cliente'),
        ),
        migrations.AddField(
            model_name='natural_person',
            name='Phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono del cliente'),
        ),
    ]
