# Generated by Django 4.1.3 on 2023-01-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_publicity_remove_bill_public_lighting_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='publicity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.publicity'),
        ),
    ]
