# Generated by Django 4.1.3 on 2023-01-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_bill_publicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='publicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.publicity'),
        ),
    ]
