# Generated by Django 4.1.3 on 2023-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(default='.\\static\\media\\images_pdf\\logo.png', max_length=300, null=True),
        ),
    ]
