# Generated by Django 4.1.3 on 2023-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='image_publicity',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
