# Generated by Django 4.1.3 on 2023-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='https://images-ext-2.discordapp.net/external/fOt8CR_wyAcTRaQXVpRKu4w5EQijqXLInJ7Djf_HWD0/https/res.cloudinary.com/dvm5lesco/image/upload/v1674918160/cld-sample-5.jpg?width=1003&height=670', max_length=400, upload_to='imagenes_ussuarios', verbose_name='imagen'),
        ),
    ]
