# Generated by Django 4.1.3 on 2023-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_publicity_image_publicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='concepts',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='details',
        ),
        migrations.AlterField(
            model_name='bill',
            name='billing_status',
            field=models.CharField(blank=True, default='pendiente', max_length=20, null=True, unique=True, verbose_name='Estado de la factura'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='default_interest',
            field=models.IntegerField(blank=True, null=True, verbose_name='IVA'),
        ),
    ]
