# Generated by Django 4.1.3 on 2023-01-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_bill_billing_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billing_status',
            field=models.CharField(blank=True, default='pendiente', max_length=20, null=True, verbose_name='Estado de la factura'),
        ),
    ]
