# Generated by Django 4.1.3 on 2023-01-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_bill_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='default_interest',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_consumption',
            field=models.FloatField(verbose_name='Total a pagar por consumo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_payout',
            field=models.FloatField(verbose_name='Total a pagar'),
        ),
    ]
