# Generated by Django 4.1.3 on 2023-01-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_bill_default_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month_consumption',
            field=models.FloatField(verbose_name='Consumo del mes'),
        ),
    ]
