# Generated by Django 4.1.3 on 2023-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_contract_stratum_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stratum_social',
            field=models.IntegerField(verbose_name='Estrato social'),
        ),
    ]
