# Generated by Django 4.1.3 on 2023-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_contract_stratum_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='image_publicity',
            field=models.FileField(default='https://res.cloudinary.com/dvm5lesco/image/upload/v1674920274/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8_wqmaht.jpg', max_length=400, upload_to='imagenes_publicidad', verbose_name='imagen publicidad'),
        ),
    ]
