# Generated by Django 4.1.3 on 2023-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_publicity_image_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='pdfs/', verbose_name='pdf factura'),
        ),
    ]
