# Generated by Django 4.1.3 on 2023-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_bill_pdf_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='public_light',
            field=models.FloatField(default=0, verbose_name='Valor de la luz publica'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='pdf', verbose_name='pdf factura'),
        ),
    ]
