# Generated by Django 4.1.3 on 2023-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_bill_public_light_alter_bill_pdf_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='C:/Users/camyj/OneDrive/Documentos/Universidad', verbose_name='pdf factura'),
        ),
    ]
