# Generated by Django 4.1.3 on 2023-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_bill_pdf_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='electronic_payment_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero de pago electronico'),
        ),
    ]
