# Generated by Django 4.1.3 on 2023-02-01 14:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_bill_electronic_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/josegabjimenez/Programming/U/5th_Semester/Software_Development/Mkaly/backmkaly/app1/static/media'), upload_to='pdf', verbose_name='pdf factura'),
        ),
    ]
