# Generated by Django 4.1.3 on 2023-02-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_bill_pdf_bill'),
        ('app1', '0041_alter_bill_bill_number'),
    ]

    operations = [
    ]
