# Generated by Django 4.1.3 on 2023-02-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=40, unique=True, verbose_name='Numero de factura'),
        ),
    ]
