# Generated by Django 4.1.3 on 2023-02-01 17:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_merge_20230201_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\sebas\\OneDrive\\Escritorio\\Ambiente virtual\\Mkaly\\backmkaly\\app1/static/media'), upload_to='pdf', verbose_name='pdf factura'),
        ),
    ]
