# Generated by Django 4.1.3 on 2023-02-01 05:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_bill',
            field=models.FileField(blank=True, max_length=4000, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\NITRO 5\\OneDrive\\Escritorio\\Proyectos\\Desarrollo l\\Mkaly\\backmkaly\\../frontmkaly/public/files'), upload_to='pdf', verbose_name='pdf factura'),
        ),
    ]
