# Generated by Django 4.1.3 on 2023-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_bill_pdf_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.IntegerField(unique=True, verbose_name='Numero de factura'),
        ),
    ]
